/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'title' : IDL.Text,
  'artist' : IDL.Text,
  'videoId' : IDL.Text,
});
export const PreferencesView = IDL.Record({
  'favoriteMood' : IDL.Text,
  'recentlyPlayed' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getPreferences' : IDL.Func([], [PreferencesView], ['query']),
  'likeSong' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'savePreferences' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'unlikeSong' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'title' : IDL.Text,
    'artist' : IDL.Text,
    'videoId' : IDL.Text,
  });
  const PreferencesView = IDL.Record({
    'favoriteMood' : IDL.Text,
    'recentlyPlayed' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getPreferences' : IDL.Func([], [PreferencesView], ['query']),
    'likeSong' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'savePreferences' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'unlikeSong' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };